apiVersion: cloudkinds.k8s.io/v1alpha1
kind: CloudProvider
metadata:
  name: {{ include "cloudkinds-servicecatalog.fullname" . }}
spec:
  webhook: http://{{ include "cloudkinds-servicecatalog.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  kinds:
  - MySQL # TODO: update our own provider dynamically with services from the catalog
