apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudkinds-servicecatalog
rules:
- apiGroups:
  - cloudkinds.k8s.io
  resources:
  - cloudresources
  verbs:
  - get
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudkinds-servicecatalog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudkinds-servicecatalog
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
